### Students Show
GET http://localhost:3000/students/1.json

### Students index action
GET http://localhost:3000/students.json

### Student Destroy
DELETE http://localhost:3000/students/1.json

### Students Create
POST http://localhost:3000/students.json
Content-Type: application/json

{  "first_name": "a",
   "last_name": "a",
   "email": "a",
   "phone_number": "a",
   "short_bio": "a",
   "linkedin_url": "a",
   "twitter_handle": "a",
   "personal_blog_url": "a",
   "online_resume_url": "a",
   "github_url": "a",
   "photo": "a"
}

### Student Update 
PATCH http://localhost:3000/students/2.json
Content-Type: application/json
    
    {"first_name": "b",
    "last_name": "b",
    "email": "a",
    "phone_number": "b",
    "short_bio": "b",
    "linkedin_url": "b",
    "twitter_handle": "b",
    "personal_blog_url": "b",
    "online_resume_url": "b",
    "github_url": "b",
    "photo": "b"
    }
 
### Skills index action
GET http://localhost:3000/skills.json


### skills show action
GET http://localhost:3000/skills/1.json
Content-Type: application/json

### Skills create action
POST http://localhost:3000/skills.json
Content-Type: application/json 

{
  "student_id": 2,
  "skills_name": "create test"
  }

### Skills Update 
PATCH http://localhost:3000/skills/2.json
Content-Type: application/json

{
  "student_id": 100,
  "skills_name": "updated name"
}

### experiences Show
GET http://localhost:3000/experiences/1.json

### experiences index action
GET http://localhost:3000/experiences.json

### experience Destroy
DELETE http://localhost:3000/experiences/1.json

### experiences Create
POST http://localhost:3000/experiences.json
Content-Type: application/json

{
    "student_id": 2,
    "start_date": "June 1",
    "end_date": "May 30",
    "company_name": "Record University",
    "details": "yes please"
}

### experience Update 
PATCH http://localhost:3000/experiences/2.json
Content-Type: application/json

    {
    "student_id": 2,
    "start_date": "June 1",
    "end_date": "May 31",
    "company_name": "Record University",
    "details": "yes please",
    }



### educations Show
GET http://localhost:3000/education/1.json

### educations index action
GET http://localhost:3000/education.json

### education Destroy
DELETE http://localhost:3000/education/1.json

### educations Create
POST http://localhost:3000/education.json
Content-Type: application/json

{
    "student_id": 1,
    "start_date": "June 1",
    "end_date": "May 30",
    "degree": "Vinyl Stuff",
    "university_name": "Record University",
    "details": "yes please",
}

### education Update 
PATCH http://localhost:3000/education/2.json
Content-Type: application/json

    {
    "student_id": 1,
    "start_date": "June 1",
    "end_date": "May 30",
    "degree": "Vinyl Stuff",
    "university_name": "Record University",
    "details": "yes please",
    }



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}